### PR TITLE
Merging to Mapbox PR

### PR DESCRIPTION
**Pull request by brennanMKE**

### CODE REVIEW

**Comment by brennanMKE** [comment]
@casademora I merged in other PRs and created this branch from yours to get it all to build and run. Could you review and give me a green light on it?

**Comment by casademora** [comment]
One thing I didn't see was an entry in the Info.plist file or a Settings.bundle key to disable the location opt out ...this caused mapbox to trigger an abort on the app previously

**Comment by brennanMKE** [comment]
Yes, I found that and added the Settings.bundle from the framework. But that may not be right.

**Comment by brennanMKE** [comment]
And I tried localizing the Settings bundle before and I am not sure how that is done correctly.

**Comment by casademora** [comment]
yeah, i would just do the disable key in the info.plist file to let the app not crash for now.

**Comment by casademora** [comment]
looks like it works

**Comment by brennanMKE** [comment]
Ok, I will merge it.

**Comment by casademora** [comment]
:+1:

**Pull request merged**
