### PR TITLE
Organized project #1

### PR DESCRIPTION
**Pull request by brennanMKE**

### CODE REVIEW

**Comment by casademora** [comment]
LGTM

**Comment by casademora** [comment]
Oh, we should merge onto develop first, then master

**Comment by brennanMKE** [comment]
@casademora I will do that next time. I think I forked it from master which is why the PR merged that way. Do you want to only merge from `develop` to `master` when preparing a release?

**Comment by aphexcx** [comment]
@brennanMKE That's the git-flow standard, yeah, but no big deal on this PR obv

**Pull request merged**
