### PR TITLE
Evan tidying up login

### PR DESCRIPTION
**Pull request by mkulumadzi**
Implemented login procedure:
- During onboarding flow
- From main menu
- When pickup request is created and user is not logged in
- When user applies to be volunteer and is not logged in

The latter three all use the same nib for a modal dialogue. The former copies this functionality, but was implemented within the collection view Brian had already created.

### CODE REVIEW

**Comment by aphexcx** [comment]
I get an exception right before scrolling to the last onboarding page, can you repro?

```
2016-01-12 20:30:09.262 GiveNow[1026:20228] Could not load the "checkmark" image referenced from a nib in the bundle with identifier "io.givenow.GiveNow"
fatal error: unexpectedly found nil while unwrapping an Optional value

    func formatButton(button: UIButton, imageName: String){
>        button.setImage(UIImage(named: imageName)!.imageWithRenderingMode(.AlwaysTemplate), forState: .Normal)
        button.tintColor = UIColor.whiteColor()
    }
```

**Comment by mkulumadzi** [comment]
I can't reproduce it. I did have a typo somewhere where that image was referred to as "checkMark", but it's fixed and not producing a bug anymore. You should see an image called "checkmark" in the Assets.xcasetts item. Do you?

**Comment by mkulumadzi** [comment]
That said, I see something I can do to prevent this from happening again (ie, not force unwrap the optional). I'll do a patch tomorrow!

**Comment by aphexcx** [comment]
Hah, interesting. My Assets.xcassets folder has a "checkMark" image. Note the capital M. I'm up-to-date on latest develop. Did you commit the case-rename?

**Pull request merged**
